### ISSUE TITLE
Need help on KTF_dual_input.py

### ISSUE THREAD

**Issue by Neetu162** [jbooz1/DeepLearningResearch#5]
@jbooz1 I am trying to run the KTF_dual_input and i am not sure what should I give as input for good_path and mal_path

**Comment by jbooz1** [comment]
Hi.   This is an old repo I had for a paper I co-authored a few years ago, so I am not up to speed with it anymore and as you might have noticed, it is not very well documented. 

However, in most cases, the good_path and the mal_path, as I remember, are referring to the files goodPermissionsFinal and malwarePermissionsFinal from the data directory. 

These are extracted permissions features from benign and malicious Android APK files.

**Comment by Neetu162** [comment]
Thanks
